# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightInfoId', models.CharField(max_length=30)),
                ('outboundOrigin', models.CharField(max_length=100)),
                ('outboundDestination', models.CharField(max_length=100)),
                ('outboundDepartureDate', models.DateTimeField()),
                ('inboundOrigin', models.CharField(max_length=100)),
                ('inboundDestination', models.CharField(max_length=100)),
                ('inboundDepartureDate', models.DateTimeField()),
                ('price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'FLIGHT_INFO',
            },
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelInfoId', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=100)),
                ('destinationDate', models.DateTimeField()),
                ('hotelName', models.CharField(max_length=100)),
                ('hotelGrade', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'HOTEL_INFO',
            },
        ),
        migrations.CreateModel(
            name='Mcontroller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=20)),
                ('pw', models.CharField(blank=True, default='', max_length=12)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_info_id', models.CharField(max_length=100)),
                ('regs_id', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=10)),
                ('headers', models.CharField(blank=True, default='', max_length=2000)),
                ('querystring', models.CharField(default='', max_length=2000)),
                ('price', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'PRICE_INFO',
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripPlanId', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('lowestPrice', models.BigIntegerField()),
            ],
            options={
                'db_table': 'PRICE_PLAN',
            },
        ),
        migrations.CreateModel(
            name='PricePlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricePlanId', models.CharField(max_length=30)),
                ('seqNo', models.BigIntegerField()),
                ('flightInfoId', models.CharField(max_length=100)),
                ('hotelInfoId', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PRICE_PLAN_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripPlanId', models.CharField(max_length=30)),
                ('userId', models.CharField(max_length=30)),
                ('pricePlanId', models.CharField(max_length=30)),
                ('startTripDate', models.DateTimeField()),
                ('endTripDate', models.DateTimeField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TRIP_PLAN',
            },
        ),
        migrations.CreateModel(
            name='TripPlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripPlanId', models.CharField(blank=True, default='', max_length=30)),
                ('gps', models.CharField(blank=True, default='', max_length=50)),
                ('locationName', models.CharField(max_length=100)),
                ('tripDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'TRIP_PLAN_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('userName', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
